#! /bin/sh

xmodmap .xmodmap-sid & # remove this 

if [[ $(xrandr --query | grep 'HDMI-1 connected') ]]; then
  xrandr --output eDP-1 --primary --mode 2880x1880 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --right-of eDP-1
  bspc monitor eDP-1 -d 1 2 3
  bspc monitor HDMI-1 -d 4 5 6
else
  bspc monitor -d 1 2 3 4 5
fi

bspc config border_width         3
bspc config borderless_monocle   false

bspc config window_gap            20
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config focused_border_color "#BF616A"
bspc config normal_border_color "#353b45"

# autostart up applications 
~/.config/polybar/launch.sh &
feh --bg-fill ~/Pictures/Wallpapers/forest.jpg
picom & 
sxhkd 
