#! /bin/sh

xmodmap .xmodmap-sid & # remove this 

~/hdmi-cable-change.sh

bspc config border_width         3
bspc config borderless_monocle   false

bspc config window_gap            20
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config focused_border_color "#BF616A"
bspc config normal_border_color "#353b45"

# autostart up applications 
feh --bg-fill ~/Pictures/Wallpapers/forest.jpg
picom & 
sxhkd 
